version: 1572186723

#
#  That's it! Setup core with
#   /c setup. You can setup
# individual instance settings
#      from the dashboard:
#     https://purecore.io/
#
#          Made with ❤
#     https://bit.ly/2Nfy0XL
#