# ----------------------------------
#
#       https://purecore.io/
#      Don't share your keys!
#
#     You can setup the plugin
#     with /purecore key <key>
#
# ----------------------------------

key: "paste_your_key_here"

# Do you need help? Contact us here
#    https://discord.gg/rhpcSnK
#
#            ▄▀▄     ▄▀▄
#           ▄█░░▀▀▀▀▀░░█▄
#       ▄▄  █░░░░░░░░░░░█  ▄▄
#      █▄▄█ █░░▀░░┬░░▀░░█ █▄▄█