name: purecore
main: io.purecore.mcplugin.spigot.Instance
author: quiquelhappy
version: 1.0.0
description: All-in-one server managment tool
commands:
  key:
    description: Saves the key and reloads the plugin
    permission: purecore.setup
    usage: /purecore key <key>
  reload:
    description: Reloads the plugin
    permission: purecore.reload
    usage: /purecore reload