main: io.purecore.mcplugin.spigot.Main
author: quiquelhappy
name: purecore
version: "1.2"
api-version: 1.13
description: A complete solution for your Minecraft Server with payments, analytics, forums, punishments and much more!
commands:
  info:
    description: Shows info about the current instance
    aliases: [purecore,c,pc,core,p]
    permission: purecore.info
    usage: Please, use /&lt;command&gt; to show the current instance information
  reload:
    description: Reloads all the core handlers with the new config if any
    aliases: [purecore reload,c reload,pc reload,core reload,p reload]
    permission: purecore.reload
    usage: Please, use /&lt;command&gt; to reload the plugin
  setup:
    description: Saves the keys and reloads the plugin
    aliases: [purecore setup,c reload,pc setup,core setup,p setup]
    permission: purecore.setup
    usage: Please, use /&lt;command&gt; to setup the plugin
  punish:
    description: Creates a new punishment
    aliases: [purecore punish,c punish,pc punish,core punish,p punish]
    permission: purecore.punishment.create
    usage: Please, use /&lt;command&gt; to create a punishment
  regenkey:
    description: Regenerates the current key hash
    aliases: [purecore regenkey,c regenkey,pc regenkey,core regenkey,p regenkey]
    permission: purecore.key.regen
    usage: Please, use /&lt;command&gt; to regen the keys